server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/noches-magicas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Para activar el Trace
logging:
  level:
    root: INFO